export const MODULE_NAME = 'PO_MODULE'

export const actionTypes = {
  JOIN_SOCKET: `${MODULE_NAME}/JOIN_SOCKET`,
  JOIN_SOCKET_SUCCESS: `${MODULE_NAME}/JOIN_SOCKET_SUCCESS`,
  JOIN_SOCKET_FAILURE: `${MODULE_NAME}/JOIN_SOCKET_FAILURE`,
  IS_LOADING: `${MODULE_NAME}/IS_LOADING`,
  SET_PO_MODULE_ERROR: `${MODULE_NAME}/SET_PO_MODULE_ERROR`,
}
