export const MODULE_NAME = 'ITEM_MODULE'

export const actionTypes = {
  LOAD_ITEMS: `${MODULE_NAME}/LOAD_ITEMS`,
  LOAD_ITEMS_SUCCESS: `${MODULE_NAME}/LOAD_SELLERS_SUCCESS`,
  LOAD_ITEMS_FAILURE: `${MODULE_NAME}/LOAD_SELLERS_FAILURE`,

  GET_ITEM: `${MODULE_NAME}/GET_ITEM`,
  GET_ITEM_SUCCESS: `${MODULE_NAME}/GET_ITEM_SUCCESS`,
  GET_ITEM_FAILURE: `${MODULE_NAME}/GET_ITEM_FAILURE`,

  UPDATE_ITEM: `${MODULE_NAME}/UPDATE_ITEM`,
  UPDATE_ITEM_SUCCESS: `${MODULE_NAME}/UPDATE_ITEM_SUCCESS`,
  UPDATE_ITEM_FAILURE: `${MODULE_NAME}/UPDATE_ITEM_FAILURE`,

  CREATE_ITEM: `${MODULE_NAME}/CREATE_ITEM`,
  CREATE_ITEM_SUCCESS: `${MODULE_NAME}/CREATE_ITEM_SUCCESS`,
  CREATE_ITEM_FAILURE: `${MODULE_NAME}/CREATE_ITEM_FAILURE`,

  DELETE_ITEM: `${MODULE_NAME}/DELETE_ITEM`,
  DELETE_ITEM_SUCCESS: `${MODULE_NAME}/DELETE_ITEM_SUCCESS`,
  DELETE_ITEM_FAILURE: `${MODULE_NAME}/DELETE_ITEM_FAILURE`,

  SEARCH_ITEM: `${MODULE_NAME}/SEARCH_ITEM`,
  SEARCH_ITEM_SUCCESS: `${MODULE_NAME}/SEARCH_ITEM_SUCCESS`,
  SEARCH_ITEM_FAILURE: `${MODULE_NAME}/SEARCH_ITEM_FAILURE`,

  CLEAR_PO_ITEMS: `${MODULE_NAME}/CLEAR_PO_ITEMS`,

  IS_LOADING: `${MODULE_NAME}/IS_LOADING`,
  SET_ITEM_MODULE_ERROR: `${MODULE_NAME}/SET_ITEM_MODULE_ERROR`,
}
