export const MODULE_NAME = 'GROUP_MODULE'

export const actionTypes = {
  LOAD_GROUPS: `${MODULE_NAME}/LOAD_GROUPS`,
  LOAD_GROUPS_SUCCESS: `${MODULE_NAME}/LOAD_GROUPS_SUCCESS`,
  LOAD_GROUPS_FAILURE: `${MODULE_NAME}/LOAD_GROUPS_FAILURE`,

  GET_GROUP: `${MODULE_NAME}/GET_GROUP`,
  GET_GROUP_SUCCESS: `${MODULE_NAME}/GET_GROUP_SUCCESS`,
  GET_GROUP_FAILURE: `${MODULE_NAME}/GET_GROUP_FAILURE`,

  UPDATE_GROUP: `${MODULE_NAME}/UPDATE_GROUP`,
  UPDATE_GROUP_SUCCESS: `${MODULE_NAME}/UPDATE_GROUP_SUCCESS`,
  UPDATE_GROUP_FAILURE: `${MODULE_NAME}/UPDATE_GROUP_FAILURE`,

  CREATE_GROUP: `${MODULE_NAME}/CREATE_GROUP`,
  CREATE_GROUP_SUCCESS: `${MODULE_NAME}/CREATE_GROUP_SUCCESS`,
  CREATE_GROUP_FAILURE: `${MODULE_NAME}/CREATE_GROUP_FAILURE`,

  DELETE_GROUP: `${MODULE_NAME}/DELETE_GROUP`,
  DELETE_GROUP_SUCCESS: `${MODULE_NAME}/DELETE_GROUP_SUCCESS`,
  DELETE_GROUP_FAILURE: `${MODULE_NAME}/DELETE_GROUP_FAILURE`,

  IS_LOADING: `${MODULE_NAME}/IS_LOADING`,
  SET_GROUP_MODULE_ERROR: `${MODULE_NAME}/SET_GROUP_MODULE_ERROR`,
}
