export const MODULE_NAME = 'AUTH_MODULE'

export const actionTypes = {
  INITIAL_AUTH: `${MODULE_NAME}/INITIAL_AUTH`,
  SET_INITIAL_AUTH_STATUS: `${MODULE_NAME}/SET_INITIAL_AUTH_STATUS`,
  SET_USER_INFO: `${MODULE_NAME}/SET_USER_INFO`,
  LOGIN: `${MODULE_NAME}/LOGIN`,
  LOGOUT: `${MODULE_NAME}/LOGOUT`,
  IS_LOADING: `${MODULE_NAME}/IS_LOADING`,
  SET_AUTH_MODULE_ERROR: `${MODULE_NAME}/SET_AUTH_MODULE_ERROR`,
}
