export const MODULE_NAME = 'SELLER_MODULE'

export const actionTypes = {
  LOAD_SELLERS: `${MODULE_NAME}/LOAD_SELLERS`,
  LOAD_SELLERS_SUCCESS: `${MODULE_NAME}/LOAD_SELLERS_SUCCESS`,
  LOAD_SELLERS_FAILURE: `${MODULE_NAME}/LOAD_SELLERS_FAILURE`,

  GET_SELLER: `${MODULE_NAME}/GET_SELLER`,
  GET_SELLER_SUCCESS: `${MODULE_NAME}/GET_SELLER_SUCCESS`,
  GET_SELLER_FAILURE: `${MODULE_NAME}/GET_SELLER_FAILURE`,

  UPDATE_SELLER: `${MODULE_NAME}/UPDATE_SELLER`,
  UPDATE_SELLER_SUCCESS: `${MODULE_NAME}/UPDATE_SELLER_SUCCESS`,
  UPDATE_SELLER_FAILURE: `${MODULE_NAME}/UPDATE_SELLER_FAILURE`,

  CREATE_SELLER: `${MODULE_NAME}/CREATE_SELLER`,
  CREATE_SELLER_SUCCESS: `${MODULE_NAME}/CREATE_SELLER_SUCCESS`,
  CREATE_SELLER_FAILURE: `${MODULE_NAME}/CREATE_SELLER_FAILURE`,

  DELETE_SELLER: `${MODULE_NAME}/DELETE_SELLER`,
  DELETE_SELLER_SUCCESS: `${MODULE_NAME}/DELETE_SELLER_SUCCESS`,
  DELETE_SELLER_FAILURE: `${MODULE_NAME}/DELETE_SELLER_FAILURE`,

  IS_LOADING: `${MODULE_NAME}/IS_LOADING`,
  SET_SELLER_MODULE_ERROR: `${MODULE_NAME}/SET_SELLER_MODULE_ERROR`,
}
