export const MODULE_NAME = 'ORGANIZATION_MODULE'

export const actionTypes = {
  GET_ORGANIZATIONS: `${MODULE_NAME}/GET_ORGANIZATIONS`,
  GET_ORGANIZATIONS_SUCCESS: `${MODULE_NAME}/GET_ORGANIZATIONS_SUCCESS`,

  IS_LOADING: `${MODULE_NAME}/IS_LOADING`,
  SET_AUTH_MODULE_ERROR: `${MODULE_NAME}/SET_AUTH_MODULE_ERROR`,
}
